### ISSUE TITLE
DB backend?

### ISSUE THREAD

**Issue by PrecociouslyDigital** [SaintsRobotics/frc-scout-2016#2]
I was looking at the db, and really the only advantage of sql is that it ties in nicely with django's native auth system. Nosql would work*, so maybe look into mongo support?

*nosql "works" like tgc card game booster packs. You normally don't get what you want, but you get what you want enough that you keep coming back to it. I am not good at metaphors.

**Comment by terabyte128** [comment]
Not sure what the advantage of using NoSQL would be. Keep in mind that one of the key points of this last year was keeping very tight relations when exporting data to Tableau. 

Seems needlessly complicated, IMO. At this level, any speed differences will be mostly nil.

**Comment by PrecociouslyDigital** [comment]
Yeah, and I realized that I could do what I wanted to do with SQL, I just had to add two columns.

**Comment by PrecociouslyDigital** [comment]
Also, I should stop writing things right before bedtime.
